sudo: false
notifications:
  email: false
language: ruby
rvm:
  - 2.5.3
env:
  - RAILS_VERSION=4.2
  - RAILS_VERSION=5.0
  - RAILS_VERSION=5.1
  - RAILS_VERSION=5.2
script:
  - bundle exec rspec --color
